const nights=window.NIGHTS;
let currentFilter='all'; let servings=2;
const app=document.querySelector('#app'); const afterToggle=document.querySelector('#afterToggle');
const FRACTIONS={'1/2':.5,'1/3':1/3,'2/3':2/3,'1/4':.25,'3/4':.75,'1/8':.125,'3/8':.375,'5/8':.625,'7/8':.875};
function fmt(x){if(Math.abs(x-Math.round(x))<.001)return String(Math.round(x)); const fr=[[.125,'1/8'],[.25,'1/4'],[1/3,'1/3'],[.375,'3/8'],[.5,'1/2'],[.625,'5/8'],[2/3,'2/3'],[.75,'3/4'],[.875,'7/8']];let w=Math.floor(x),d=x-w,b=fr.reduce((a,z)=>Math.abs(z[0]-d)<Math.abs(a[0]-d)?z:a,fr[0]);return (w?w+' ':'')+b[1]}
function nval(s){s=s.trim(); if(FRACTIONS[s]!=null)return FRACTIONS[s]; if(/^\d+(\.\d+)?$/.test(s))return +s; const m=s.match(/^(\d+)\s+(\d\/\d)$/); if(m)return +m[1]+(FRACTIONS[m[2]]||0); return null}
function scaleIngredient(s){const factor=servings/4; let m=s.match(/^(\d+\s+\d\/\d|\d+\/\d|\d+(?:\.\d+)?)(?:-(\d+\s+\d\/\d|\d+\/\d|\d+(?:\.\d+)?))?(.*)$/); if(!m)return s; let a=nval(m[1]); if(a==null)return s; let out=fmt(a*factor); if(m[2]){let b=nval(m[2]); if(b!=null)out+='-'+fmt(b*factor)} return out+m[3]}
function uniqIngredients(n){let a=[]; n.recipes.forEach(r=>r[1].forEach(x=>a.push(scaleIngredient(x)))); return [...new Set(a)]}
function render(){app.innerHTML=''; const filtered=currentFilter==='all'?nights:nights.filter(n=>n.tags.includes(currentFilter)); filtered.forEach((n,i)=>{const sec=document.createElement('section');sec.className='night';sec.id=n.id; const dark=n.after&&!afterToggle.checked;
sec.innerHTML=`<div class="night-head"><div class="passport">Passport No. ${String(nights.indexOf(n)+1).padStart(2,'0')}</div><h2>${n.title}</h2><div class="city">${n.city}</div><p class="tagline">${n.tagline}</p><div class="badges"><span class="badge">${n.mood}</span><span class="badge flower-badge">${n.flowers}</span>${n.tags.map(t=>`<span class="badge tag">${t}</span>`).join('')}</div></div>
<div class="details"><div class="detail"><small>Flowers</small><div>${n.flowers}</div></div><div class="detail"><small>Dress</small><div>${n.dress}</div></div><div class="detail"><small>Sound</small><div>${n.music}</div></div><div class="detail"><small>Serves tonight</small><div>${servings} ${servings===2?'lovers':'people'}</div></div></div>
<div class="menu-wrap"><h3>Tonight’s menu</h3><div class="menu">${n.menu.map(x=>`<div class="menu-item">${x}</div>`).join('')}</div></div>
<div class="playful"><strong>Before dinner: write it down</strong><div>${n.playful}</div></div>
<div class="dare-box"><div><strong>Dare Deck</strong><p>Write your own cards first, or let Velvet Passport deal one.</p></div><button class="draw-dare" data-id="${n.id}">Draw a dare</button><div class="dare-result" id="dare-${n.id}">Folded cards > algorithms. But both are fun.</div></div>
<div class="ritual ${dark?'blurred':''}"><strong>${n.after?'After Dark ritual':'Date-night ritual'}</strong><div class="ritual-text">${n.ritual}</div></div>
<div class="recipes"><div class="recipes-title"><h3>Recipes</h3><span>scaled from 4 → <b>${servings}</b></span></div><div class="recipe-grid">${n.recipes.map(r=>`<article class="recipe"><div class="serves">Serves ${servings}</div><h4>${r[0]}</h4><div class="recipe-columns"><ul>${r[1].map(x=>`<li>${scaleIngredient(x)}</li>`).join('')}</ul><ol>${r[2].map(x=>`<li>${x}</li>`).join('')}</ol></div></article>`).join('')}</div></div>
<details class="grocery"><summary>Grocery checklist · scaled for ${servings}</summary><div class="grocery-list">${uniqIngredients(n).map((x,j)=>`<label><input type="checkbox" data-key="${n.id}-${servings}-${j}"> ${x}</label>`).join('')}</div></details>`; app.appendChild(sec);});restoreChecks(); bindDares();}
function restoreChecks(){document.querySelectorAll('.grocery input').forEach(c=>{c.checked=localStorage.getItem('vp-'+c.dataset.key)==='1';c.addEventListener('change',()=>localStorage.setItem('vp-'+c.dataset.key,c.checked?'1':'0'))})}
function bindDares(){document.querySelectorAll('.draw-dare').forEach(b=>b.addEventListener('click',()=>{let n=nights.find(x=>x.id===b.dataset.id);let result=n.dares[Math.floor(Math.random()*n.dares.length)];document.querySelector('#dare-'+n.id).textContent=result}))}
afterToggle.addEventListener('change',render);
document.querySelectorAll('.navchip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.navchip').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()}));
document.querySelectorAll('.serve').forEach(b=>b.addEventListener('click',()=>{servings=+b.dataset.servings;document.querySelectorAll('.serve').forEach(x=>x.classList.toggle('active',+x.dataset.servings===servings));render()}));document.querySelector('.serve[data-servings="2"]').classList.add('active');
document.querySelector('#surprise').addEventListener('click',()=>{const pool=currentFilter==='all'?nights:nights.filter(n=>n.tags.includes(currentFilter));const n=pool[Math.floor(Math.random()*pool.length)];location.hash=n.id;setTimeout(()=>document.querySelector('#'+n.id)?.scrollIntoView({behavior:'smooth'}),40)});render();